//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPAOnetStackOverflowESEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceEstudianteCurso
    {
        public int Id { get; set; }
        public int EstudianteID { get; set; }
        public int CursoID { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
