//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPAOnetStackOverflowESEntidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPAOnetStackOverflowESBaseDeDatosEntities : DbContext
    {
        public UPAOnetStackOverflowESBaseDeDatosEntities()
            : base("name=UPAOnetStackOverflowESBaseDeDatosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<EnlaceEstudianteCurso> EnlaceEstudianteCursoes { get; set; }
    }
}
